import React from "react";
import Label from "../../components/label/Label";
import {
  Wrapper,
  Container,
  Container1,
  Container2,
  Item1,
  Item2,
  Item3,
  FlexItem1,
  FlexItem2,
  FlexItem3,
  StockContainer,
  StockCompanyContainer,
  GainLoserTableProps,
  Container3,
} from "./styles";
import Divider from "../../components/divider/Divider";
export const GainLoserTable = ({
  label,

  ...props
}: GainLoserTableProps) => {
  return (
    <Wrapper>
      <Container1>
        <Item1>
          <Label
            fontSize={"0.75rem"}
            color={"#0F1825;"}
            fontWeight={700}
            fontStyle={"normal"}
            lineHeight={"1rem"}
            label="Symbol"
            fontFamily="SourceSansPro-Bold"
          />
        </Item1>
        <Item2>
          <Label
            fontSize={"0.75rem"}
            color={"#0F1825;"}
            fontWeight={700}
            fontStyle={"normal"}
            lineHeight={"1rem"}
            label="Price"
            fontFamily="SourceSansPro-Bold"
          />
        </Item2>
        <Item3>
          <Label
            fontSize={"0.75rem"}
            color={"#0F1825;"}
            fontWeight={700}
            fontStyle={"normal"}
            lineHeight={"1rem"}
            label="Change"
            fontFamily="SourceSansPro-Bold"
          />
        </Item3>
      </Container1>
      <Container2>
        <Divider
          borderColor={"#EEF3F5"}
          horizontal={true}
          borderHeight={"1px"}
        ></Divider>
      </Container2>
      <Container>
        <FlexItem1>
          <StockContainer>
            <Label
              fontSize={"0.875rem"}
              color={"#0F1825"}
              fontWeight={400}
              fontStyle={"normal"}
              lineHeight={"1.5rem"}
              label="AMZN"
              fontFamily="SourceSansProBold"
            />
          </StockContainer>
          <StockCompanyContainer>
            <Label
              fontSize={"0.75rem"}
              color={"#374253;"}
              fontWeight={400}
              fontStyle={"normal"}
              lineHeight={"1rem"}
              label="Amazon..."
              fontFamily="SourceSansProBold"
            />
          </StockCompanyContainer>
        </FlexItem1>
        <FlexItem2>
          <Label
            fontSize={"0.875rem"}
            color={"#0F1825"}
            fontWeight={400}
            fontStyle={"normal"}
            lineHeight={"1.5rem"}
            label="$3,054.03"
            fontFamily="SourceSansProBold"
          />
        </FlexItem2>
        <FlexItem3>
          <Label
            fontSize={"0.875rem"}
            color={"#ffff"}
            fontWeight={700}
            fontStyle={"normal"}
            lineHeight={"1rem"}
            label="+$2.03"
            fontFamily="SourceSansProBold"
          />
        </FlexItem3>
      </Container>
      <Container3>
        <Divider
          borderColor={"#EEF3F5"}
          horizontal={true}
          borderHeight={"1px"}
        ></Divider>
      </Container3>
    </Wrapper>
  );
};
